---
- hosts: dns
  become: yes
  tasks:
   - name: Install necessary packages
     apt:
      pkg: 
       - pdns-server
       - pdns-backend-sqlite3
       - sqlite3
      state: latest
   - name: Place pdns config file
     copy:
       src: "{{ playbook_dir }}/pdns.conf"
       dest: /etc/powerdns/pdns.conf
       owner: pdns
       group: pdns
       mode: 0644
   - name: Place pdns database dir
     file:
       path: /var/lib/powerdns
       owner: pdns
       group: pdns
       state: directory
   - name: Set up pdns database
     shell: sqlite3 /var/lib/powerdns/pdns.sqlite3 < /usr/share/doc/pdns-backend-sqlite3/schema.sqlite3.sql
     args:
      creates: /var/lib/powerdns/pdns.sqlite3
   - name: Start powerdns
     service:
       name: pdns
       state: started

